config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
		@time = Time.now
  end

  def goodbye
		@files = Dir.glob('*')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>It was nice having you here.</p>
<p>
	Say <%= link_to "Hello", say_hello_path %> again.
</p>
<p>
	Playtime -
	The files are in the directory:
	<% @files.each do |file| %>
		<ul><%= file %></ul>
	<% end %>	
</p>

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<p>Find me in app/views/say/hello.html.erb</p>
<p>
	It is now <%= @time %> and the sum of 1 and 2 is <%= 1+2 %>
</p>
<p>
	Playtime - addition 1 and 2 : <%= 1+2 %>
</p>
<p>
	Playtime - concatenation cow + boy : <%= "cow" + "boy" %>	
</p>
<p>
	Playtime - Time in one hour : <%= 2.hour.from_now.localtime %>
</p>
<p>
	Time to say
	<%= link_to "Goodbye", say_goodbye_path %>!
</p>